project:
  type: website
  output-dir: docs

website:
  title: "HCannon001.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Projects"
        menu: 
          - href: canadian_births.qmd
          - href: Attendance.qmd
          - href: TheOfficeLineAnalysis.qmd
          - href: Game_Simulations.qmd
          - href: Project 4.qmd
          - href: SQL_Connection.qmd
      - text: "Presentation"
        menu: 
          - href: SlideShow.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

