project:
  type: website
  output-dir: docs

website:
  title: "HCannon001.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Tidy Tuesday Visualizations"
        menu: 
          - href: canadian_births.qmd
          - href: Attendance.qmd
      - text: "Mini Project 2"
        menu: 
          - href: TheOfficeLineAnalysis.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

